## 지도 학습을 위한 데이터 분리 전처리 작업

### 1) zip 함수를 이용해 X, Y 분리

In [2]:
X,y = zip(['a',1], ['b',2], ['c',3])
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


In [4]:
sequences = [['a',1],['b',2],['c',3]]
X, y = zip(*sequences)
print(X)
print(y)

('a', 'b', 'c')
(1, 2, 3)


### 2) 데이터프레임을 이용해 분리



In [9]:
import pandas as pd
values = [['당신에게 드리는 마지막 혜택!',1],
          ['내일 뵐 수 있을지 확인 부탁드...',0],
          ['도연씨. 잘 지내시죠? 오랜만입...', 0],
          ['(광고) AI로 주가를 예측할 수 있다!',1]]
columns = ['메일 본문', '스팸 메일 유무']
df = pd.DataFrame(values, columns = columns)
df

메일 본문  스팸 메일 유무
0        당신에게 드리는 마지막 혜택!         1
1    내일 뵐 수 있을지 확인 부탁드...         0
2    도연씨. 잘 지내시죠? 오랜만입...         0
3  (광고) AI로 주가를 예측할 수 있다!         1

In [11]:
X = df['메일 본문']
y = df['스팸 메일 유무']
print(X)
print(y)

0          당신에게 드리는 마지막 혜택!
1      내일 뵐 수 있을지 확인 부탁드...
2      도연씨. 잘 지내시죠? 오랜만입...
3    (광고) AI로 주가를 예측할 수 있다!
Name: 메일 본문, dtype: object
0    1
1    0
2    0
3    1
Name: 스팸 메일 유무, dtype: int64


### 3) Numpy를 이용한 분리

In [13]:
import numpy as np
ar = np.arange(0,16).reshape((4,4))
print(ar)
X= ar[:,:3]
print(X)
y = ar[:, 3]
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
[ 3  7 11 15]
